#!/bin/bash
#PBS -N osca_AU
#PBS -A UQ-IMB-CNSG
#PBS -l select=1:ncpus=20:mem=50gb
#PBS -q normal
#PBS -l walltime=10:00:00
#PBS -V

# This script runs MWAS in unadjusted vs adjusted methylation AUS and NL methylation datasets 

###########################
## Set working directory ##
###########################

wd=/gpfs/gpfs01/polaris/Q0286/BRAIN-MEND/2019_AUS_ALS_PCTG_DNAm/data/input_files

#################################
## Change to working directory ##
#################################

cd $wd

#########################
## path to OSCA binary ##
#########################

osca=/gpfs/gpfs01/polaris/Q0286/BRAIN-MEND/2019_AUS_ALS_PCTG_DNAm/software/osca

#####################################################
## Export methylation values in OSCA binary format ##
#####################################################

# The Australian/Netherlands unadjusted ALS datasets

export betas_aus="AUS_ALS_PCTG_qced_normalized_DNAm-autosomes-no-xreact-no-SNP-sd0.02"
export betas_nl="Netherlands_ALS_qced_normalized_DNAm-autosomes-no-xreact-no-SNP-sd0.02"

# The Australian/Netherlands adjuted ALS datasets

export betas_aus_adj="AUS_ALS_PCTG_qced_normalized_DNAm_autosomes_adjusted-no-xreact-no-SNP-sd0.02"
export betas_nl_adj="Netherlands_ALS_qced_normalized_autosomes_adjusted-no-xreact-no-SNP-sd0.02"

# Export phenotype files

export pheno_aus="AUS_ALS_PCTG_case_control_phenotype.txt"
export pheno_nl="Netherlands_ALS_case_control_phenotype.txt"


##################################################################################################
## Run linear regression without covariates, with 10PCs calculated from the ORM, MOA and MOMENT ##
##################################################################################################

[ ! -d "../../results" ] && mkdir -p "../../results"

[ ! -d "../../results/MWAS" ] && mkdir -p "../../results/MWAS"

################################
### Calculate 10PCs from ORM ###

$osca --orm ${betas_aus} --pca 10 --out ../../results/MWAS/${betas_aus}-10PCS --thread-num 20

$osca --orm  ${betas_aus_adj} --pca 10 --out  ../../results/MWAS/${betas_aus_adj}-10PCS  --thread-num 20

$osca --orm ${betas_nl}  --pca 10 --out ../../results/MWAS/${betas_nl}-10PCS  --thread-num 20

$osca --orm  ${betas_nl_adj} --pca 10 --out ../../results/MWAS/${betas_nl_adj}-10PCS  --thread-num 20

#######################################
### Linear regression no covariates ###


$osca --befile ${betas_aus} --linear --pheno $pheno_aus --out ../../results/MWAS/${betas_aus}-noCOVS  --thread-num 20

$osca --befile  ${betas_aus_adj} --linear --pheno $pheno_aus --out  ../../results/MWAS/${betas_aus_adj}-noCOVS  --thread-num 20

$osca --befile ${betas_nl} --linear --pheno $pheno_nl --out ../../results/MWAS/ ${betas_nl}-noCOVS  --thread-num 20

$osca --befile ${betas_nl_adj}  --linear --pheno $pheno_nl --out ../../results/MWAS/${betas_nl_adj}-noCOVS --thread-num 20

##############################################
### Linear regression with 10PCs from ORM  ###


$osca --befile ${betas_aus} --linear --pheno $pheno_aus --qcovar ../../results/MWAS/${betas_aus}-10PCS.eigenvec --out ../../results/MWAS/${betas_aus}-with-10PCS --thread-num 20

$osca --befile  ${betas_aus_adj} --linear --pheno $pheno_aus --qcovar  ../../results/MWAS/${betas_aus_adj}-10PCS.eigenvec --out  ../../results/MWAS/${betas_aus_adj}-with-10PCS --thread-num 20

$osca --befile ${betas_nl} --linear --pheno $pheno_nl --qcovar  ../../results/MWAS/${betas_nl}-10PCS.eigenvec --out  ../../results/MWAS/${betas_nl}-with-10PCS --thread-num 20

$osca --befile ${betas_nl_adj}  --linear --pheno $pheno_nl --qcovar  ../../results/MWAS/${betas_nl_adj}-10PCS.eigenvec --out ../../results/MWAS/${betas_nl_adj}-with-10PCS --thread-num 20


######################
######   MOA    ######


$osca --befile ${betas_aus} --orm ${betas_aus} --moa --pheno $pheno_aus --out ../../results/MWAS/${betas_aus}-MOA --thread-num 20

$osca --befile  ${betas_aus_adj} --orm ${betas_aus_adj} --moa --pheno $pheno_aus --out  ../../results/MWAS/${betas_aus_adj}-MOA --thread-num 20

$osca --befile ${betas_nl} --orm  ${betas_nl} --moa --pheno $pheno_nl --out  ../../results/MWAS/${betas_nl}-MOA --thread-num 20

$osca --befile ${betas_nl_adj} --orm ${betas_nl_adj} --moa --pheno $pheno_nl --out ../../results/MWAS/${betas_nl_adj}-MOA --thread-num 20


#########################
######   MOMENT    ######


$osca --befile ${betas_aus} --orm-alg 1 --moment --pheno $pheno_aus --out ../../results/MWAS/${betas_aus}-MOMENT --thread-num 20

$osca --befile  ${betas_aus_adj} --orm-alg 1 --moment --pheno $pheno_aus --out  ../../results/MWAS/${betas_aus_adj}-MOMENT --thread-num 20

$osca --befile ${betas_nl} --orm-alg 1 --moment --pheno $pheno_nl --out  ../../results/MWAS/${betas_nl}-MOMENT --thread-num 20

$osca --befile ${betas_nl_adj} --orm-alg 1 --moment --pheno $pheno_nl --out ../../results/MWAS/${betas_nl_adj}-MOMENT --thread-num 20
